development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: evry_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: evry_test
  username: root
  password:
